name: DevSecOps Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
#  sonarcloud:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          # Disabling shallow clone is recommended for improving relevancy of reporting
#          fetch-depth: 0
#      - name: SonarCloud Scan
#        run: ./mvnw -Dmaven.test.skip=true -X -B verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=jpetstore -Dsonar.organization=default -Dsonar.login=d218cbce2137ce83403595d0116ec8046bfbbeb6
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: d218cbce2137ce83403595d0116ec8046bfbbeb6

  snyk:
    runs-on: ubuntu-latest
#    needs: sonarcloud
    steps:
      - uses: actions/checkout@v2
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/Maven@master # For node projects, change accordingly
        env:
          SNYK_TOKEN: dd2cc2e7-882e-4a96-9d2d-527da5cb745a
        with:
          command: monitor

  zap_scan:
    runs-on: ubuntu-latest
    name: zap
    needs: snyk
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://test.com' # Change URL or IP of your target application
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
